[package]
name = 'tok'
version = '0.3.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'tok'

[dependencies]
extendr-api = {git = "https://github.com/extendr/extendr.git", features = ["serde"]}
tokenizers = '0.13.3'
anstyle = '0.3.5'
serde = "*"
