[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/extendr/extendr.git"]
git = "https://github.com/extendr/extendr.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"